version: '3.6'

services:
  hmdns:
    extends:
      file: compose-template/compose.yml
      service: hmdns
    container_name: 'localbuild-hmdns'
    image: "localbuild-hmdns:latest"
    build:
      context: .
      dockerfile: Containerfile
    volumes:
      - hmdns-config:/mnt:Z  # don't save config

volumes:
  hmdns-config:
    name: 'localbuild-hmdns-config'